version: "2"
services:
  db:
    ports:
      - "5432:5432"
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mg4
    volumes:
      - .:/opt

  api:
    build:
      context: .
      dockerfile: .dev.dockerfile
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
        - no_proxy
        - NO_PROXY
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/opt
